version: '3'

services:
    # Etherpad: real-time collaborative document editing
    etherpad:
        image: jitsi/etherpad
        ports:
        - 9001:9001
        networks:
            meet.jitsi:
                aliases:
                    - etherpad.meet.jitsi
